name: issue-notify

on:
  issues:
    types: [opened,assigned,closed,reopened]
  issue_comment:
    types: [created]
  pull_request:
    types: [closed,assigned,converted_to_draft,ready_for_review,review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: zmughal-github-actions/events-to-irc@main
        with:
          target-notifications: true
          # repository_owner: ...
          # irc-channel: ...
          # irc-server: ...
          # irc-port: ...
          # irc-nickname: ...
          # irc-tls: ...
          # irc-notice: ...
